sudo: required
services:
  - docker
language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" wallaby/docker-ci;
    docker push USER/REPO;
    fi
